### ISSUE TITLE
reminder to add close bracket for temperatureCurve in Echo.cfg

### ISSUE THREAD

**Issue by Growflavor** [GregroxMun/Seven-Worlds-of-SLIPPIST-1#4]
GameData/SLIPPIST-1/KopernicusFiles/CelestialBodies/4-Echo.cfg

note the missing close bracket:

`key =	5000000	210	-4.09836E-06	0.00000E+00			
temperatureSunMultCurve`

suggested change:

`key =	120000	230	0.00000E+00	-4.09836E-06
key =	5000000	210	-4.09836E-06	0.00000E+00			
}
temperatureSunMultCurve				
{				
key =	0	1	0.00000E+00	-6.00000E-05`

**Comment by WhirligigGirl** [comment]
I thought I'd already fixed it just a few minutes ago, but I actually fixed a _different_ closing bracket. I've just fixed the one you found as well.
